// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __compoisson2_h__
#define __compoisson2_h__

#include "compoisson2_RcppExports.h"

#endif // __compoisson2_h__
