# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute COM-Poisson Normalizing Constant
#'
#' Computes the normalizing constant in the COM-Poisson model for given values
#' of the parameters.
#'
#' \code{com_compute_z} computes the COM-Poisson normalizing constant \deqn{
#' }{z = Sum (lambda^j)/(j!^nu) }\deqn{ z = \sum_{i=0}^\infty
#' \frac{\lambda^j}{(j!)^\nu} }{z = Sum (lambda^j)/(j!^nu) }\deqn{ }{z = Sum
#' (lambda^j)/(j!^nu) } to the specified precision. If no precision is
#' specified, then the package default is used.
#'
#' \code{com_compute_log_z} is equivalent to \code{log(com_compute_z(lambda,
#' nu))} but provudes additional precision.
#'
#' @aliases com_compute_z com_compute_log_z
#' @param lambda Lambda value in COM-Poisson distribution
#' @param nu Nu value in COM-Poisson distribution
#' @param log.error Precision in the log of the normalizing constant
#' @return The normalizing constant as a real number with specified precision.
#' @author Jeffrey Dunn
#' @seealso \code{\link{com.fit}}
#' @references Shmueli, G., Minka, T. P., Kadane, J. B., Borle, S. and
#' Boatwright, P., \dQuote{A useful distribution for fitting discrete data:
#' Revival of the Conway-Maxwell-Poisson distribution,} J. Royal Statist. Soc.,
#' v54, pp. 127-142, 2005.
#' @keywords models
#' @examples
#'
#' data(insurance)
#' fit = com.fit(Lemaire)
#' z = com_compute_z(fit$lambda, fit$nu)
#'
#' @export
com_compute_z <- function(lambda, nu, log_error_z = 1e-6, maxit_z = 10000L) {
    .Call('compoisson_com_compute_z', PACKAGE = 'compoisson', lambda, nu, log_error_z, maxit_z)
}

#' @export
com_compute_log_z <- function(lambda, nu, log_error_z = 1e-6, maxit_z = 10000L) {
    .Call('compoisson_com_compute_log_z', PACKAGE = 'compoisson', lambda, nu, log_error_z, maxit_z)
}

#' @export
com_compute_log_z_approx <- function(lambda, nu) {
    .Call('compoisson_com_compute_log_z_approx', PACKAGE = 'compoisson', lambda, nu)
}

#' @export
logsumexp <- function(x) {
    .Call('compoisson_logsumexp', PACKAGE = 'compoisson', x)
}

#' @export
logdiffexp <- function(x, y) {
    .Call('compoisson_logdiffexp', PACKAGE = 'compoisson', x, y)
}

#' @export
com_compute_log_z_old <- function(lambda, nu, log_error_z = 0.0001, maxit_z = 10000L) {
    .Call('compoisson_com_compute_log_z_old', PACKAGE = 'compoisson', lambda, nu, log_error_z, maxit_z)
}

#' The COM-Poisson Distribution
#'
#' Probability mass function and random generation for the COM-Poisson
#' distribution for given values of the parameters.
#'
#' Computes the probability mass function of the COM-Poisson distribution
#' \deqn{ }{f(x) = (1/Z) (lambda^x)/(x!^nu).}\deqn{ f(x) =
#' \frac{1}{Z(\lambda,\nu)}\frac{\lambda^x}{(x!)^\nu}. }{f(x) = (1/Z)
#' (lambda^x)/(x!^nu).}\deqn{ }{f(x) = (1/Z) (lambda^x)/(x!^nu).}
#'
#' @aliases dcom pcom qcom rcom 
#' @param x level to evaluate the PMF at
#' @param lambda value of lambda parameter
#' @param nu value of nu parameter
#' @param z normalizing constant, computed if not specified
#' @param n number of random values to return
#' @param log.z natural log of z
#' @return \code{dcom} gives the probability that a random COM-Poisson variable
#' X takes value x.  \code{rcom} gives a vector of \code{n} random values
#' sampled from the COM-Poisson distribution.
#' @author Jeffrey Dunn
#' @seealso \code{\link{com.loglikelihood}}, \code{\link{com.log.density}}
#' @references Shmueli, G., Minka, T. P., Kadane, J. B., Borle, S. and
#' Boatwright, P., \dQuote{A useful distribution for fitting discrete data:
#' Revival of the Conway-Maxwell-Poisson distribution,} J. Royal Statist. Soc.,
#' v54, pp. 127-142, 2005.
#' @keywords models
#' @export
dcom <- function(x, lambda, nu, z = NA_real_, log_p = FALSE, log_error_z = 1e-6, maxit_z = 10000L, parallel = FALSE) {
    .Call('compoisson_dcom', PACKAGE = 'compoisson', x, lambda, nu, z, log_p, log_error_z, maxit_z, parallel)
}

#' @rdname dcom
#' @export
pcom <- function(q, lambda, nu, z = NA_real_, log_p = FALSE, log_error_z = 1e-6, maxit_z = 10000L, parallel = FALSE) {
    .Call('compoisson_pcom', PACKAGE = 'compoisson', q, lambda, nu, z, log_p, log_error_z, maxit_z, parallel)
}

#' @rdname dcom
#' @export
qcom <- function(p, lambda, nu, z = NA_real_, log_p = FALSE, log_error_z = 1e-6, maxit_z = 10000L, parallel = FALSE) {
    .Call('compoisson_qcom', PACKAGE = 'compoisson', p, lambda, nu, z, log_p, log_error_z, maxit_z, parallel)
}

#' @rdname dcom
#' @export
rcom <- function(n, lambda, nu, z = NA_real_, log_error_z = 1e-6, maxit_z = 10000L, parallel = FALSE) {
    .Call('compoisson_rcom', PACKAGE = 'compoisson', n, lambda, nu, z, log_error_z, maxit_z, parallel)
}

#' Computes Expectation of a Function of a COM-Poisson Random Variable
#'
#' Computes an expectation of a function of a COM-Poisson random variable.
#'
#' Computes the expectation \eqn{E[f(X)]}{E[f(X)]} where X is a COM-Poisson
#' random variable.
#'
#' @param f function taking as a single argument the value of x
#' @param lambda value of lambda parameter
#' @param nu value of nu parameter
#' @param log.error precision in the log of the expectation
#' @return The expectation as a real number.
#' @author Jeffrey Dunn
#' @seealso \code{\link{com.mean}}, \code{\link{com.var}},
#' \code{\link{com.fit}}
#' @references Shmueli, G., Minka, T. P., Kadane, J. B., Borle, S. and
#' Boatwright, P., \dQuote{A useful distribution for fitting discrete data:
#' Revival of the Conway-Maxwell-Poisson distribution,} J. Royal Statist. Soc.,
#' v54, pp. 127-142, 2005.
#' @keywords models
#' @export
com_log_mean <- function(lambda, nu, log_error = 1e-6, maxit = 1e6L, z = NA_real_, log_error_z = 1e-6, maxit_z = 10000L, parallel = FALSE) {
    .Call('compoisson_com_log_mean', PACKAGE = 'compoisson', lambda, nu, log_error, maxit, z, log_error_z, maxit_z, parallel)
}

#' @export
com_log_mean_approx <- function(lambda, nu) {
    .Call('compoisson_com_log_mean_approx', PACKAGE = 'compoisson', lambda, nu)
}

#' @export
com_mean <- function(lambda, nu, log_error = 1e-6, maxit = 1e6L, z = NA_real_, log_error_z = 1e-6, maxit_z = 10000L, parallel = FALSE) {
    .Call('compoisson_com_mean', PACKAGE = 'compoisson', lambda, nu, log_error, maxit, z, log_error_z, maxit_z, parallel)
}

#' @export
com_log_var <- function(lambda, nu, log_error = 1e-6, maxit = 1e6L, z = NA_real_, log_error_z = 1e-6, maxit_z = 10000L, parallel = FALSE) {
    .Call('compoisson_com_log_var', PACKAGE = 'compoisson', lambda, nu, log_error, maxit, z, log_error_z, maxit_z, parallel)
}

#' @export
com_var <- function(lambda, nu, log_error = 1e-6, maxit = 1e6L, z = NA_real_, log_error_z = 1e-6, maxit_z = 10000L, parallel = FALSE) {
    .Call('compoisson_com_var', PACKAGE = 'compoisson', lambda, nu, log_error, maxit, z, log_error_z, maxit_z, parallel)
}

#' @export
com_log_var_approx <- function(lambda, nu) {
    .Call('compoisson_com_log_var_approx', PACKAGE = 'compoisson', lambda, nu)
}

#' @export
com_var_approx <- function(lambda, nu) {
    .Call('compoisson_com_var_approx', PACKAGE = 'compoisson', lambda, nu)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('compoisson_RcppExport_registerCCallable', PACKAGE = 'compoisson')
})
