# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
compute_log_z <- function(lambda, nu, log_error = 0.001, maxit = 100L) {
    .Call('compoisson2_compute_log_z', PACKAGE = 'compoisson2', lambda, nu, log_error, maxit)
}

#' @export
logsumexp <- function(x) {
    .Call('compoisson2_logsumexp', PACKAGE = 'compoisson2', x)
}

